spring:
  application:
    name: spotease-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/spotease
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

spotease:
  encryption:
    key: ${ENCRYPTION_KEY}
  spotify:
    client-id: ${SPOTIFY_CLIENT_ID:changeme}
    client-secret: ${SPOTIFY_CLIENT_SECRET:changeme}
    redirect-uri: http://localhost:8080/api/auth/spotify/callback
